# Configuración de puerto y nombre de aplicación
server.port=8080
spring.application.name=GameVault

# (Opcional) Usamos H2 en memoria para que Spring Data JPA pueda arrancar feliz
# sin necesidad de tener un servidor MySQL encendido.
spring.datasource.url=jdbc:mysql://localhost:3306/gamevaultdb?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=dnf8jpcu1
cloudinary.api_key=471766721845585
cloudinary.api_secret=1ufu9-syFOQPO5kEXZuBbH2eqe0